import UIKit
import PlaygroundSupport


class ViewController: UIViewController {
    private let totalLabel = UILabel()

    override func viewDidLoad() {
        super.viewDidLoad()

        view.backgroundColor = .cyan

        totalLabel.translatesAutoresizingMaskIntoConstraints = false

        totalLabel.text = "111222"
        view.addSubview(totalLabel)

        NSLayoutConstraint.activate([
            totalLabel.centerXAnchor.constraint(equalTo: view.centerXAnchor),
            totalLabel.centerYAnchor.constraint(equalTo: view.centerYAnchor),
        ])


        let total = sum(10, 20, 30)
        let average = sum(10, 20, 30) / 3

        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...

        totalLabel.text = String(total)

        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
        // ...
    }

    func sum(_ num1: Int, _ num2: Int, _ num3: Int) -> Int {

        num1 + num2 + num3
    }
}


PlaygroundPage.current.liveView = ViewController()
